### ISSUE TITLE
docu needs config included

### ISSUE THREAD

**Issue by mxriverlynn** [mxriverlynn/Albacore#111]
from a comment on 0.2.0.preview2 blog post comment.

---

Seems you are missing the following import in the docu.rb file (i am not a ruby expert, so I am guessing here:)):

require 'albacore/config/docuconfig'

I added the above import and then things seems to work.

Untill i added the import I got the following error (full trace included):

PS C:\temp\ruby> rake --trace

(in C:/temp/ruby)

rake aborted!

uninitialized constant Configuration::Docu

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2503:in `const_missing'

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2503:in `const_missing'

C:/IronRuby/lib/ironruby/gems/1.8/gems/albacore-0.2.0.preview2/lib/albacore/docu.rb:6

C:/IronRuby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:30:in `require'

C:/IronRuby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:30:in `require'

C:/IronRuby/lib/ironruby/gems/1.8/gems/albacore-0.2.0.preview2/lib/albacore.rb:8

C:/IronRuby/lib/ironruby/gems/1.8/gems/albacore-0.2.0.preview2/lib/albacore.rb:8:in `each'

C:/IronRuby/lib/ironruby/gems/1.8/gems/albacore-0.2.0.preview2/lib/albacore.rb:8

C:/IronRuby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'

C:/IronRuby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'

C:/temp/ruby/rakefile.rb:3

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in `load'

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in `raw_load_rakefile'

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2017:in `load_rakefile'

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2016:in `load_rakefile'

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2000:in `run'

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'

C:/IronRuby/lib/ironruby/gems/1.8/gems/rake-0.8.7/bin/rake:31

C:/IronRuby/bin/rake:19:in `load'

C:/IronRuby/bin/rake:19

**Comment by mxriverlynn** [comment]
fixed missing config for docu task. closed by e3cf0ee2c49c77e28db0774bb7d64b70b208841f
