### ISSUE TITLE
ZipTask additonal_files property fails with RubyInstaller 1.9.2

### ISSUE THREAD

**Issue by jmeridth** [mxriverlynn/Albacore#156]
When I try to use the additional_files property with RubyInstaller 1.9.2 installed I get a stack trace.

``` bash
rake aborted!
undefined method `reject' for "installagentservice.bat":String
c:/Ruby192/lib/ruby/gems/1.9.1/gems/albacore-0.2.6/lib/albacore/zipdirectory.rb:100:in `zip_additional'
c:/Ruby192/lib/ruby/gems/1.9.1/gems/albacore-0.2.6/lib/albacore/zipdirectory.rb:30:in `block in execute'
c:/Ruby192/lib/ruby/gems/1.9.1/gems/rubyzip-0.9.4/lib/zip/zip.rb:1413:in `open'
c:/Ruby192/lib/ruby/gems/1.9.1/gems/albacore-0.2.6/lib/albacore/zipdirectory.rb:28:in `execute'
c:/Ruby192/lib/ruby/gems/1.9.1/gems/albacore-0.2.6/lib/albacore/support/createtask.rb:24:in `block in zip'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:634:in `call'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:629:in `each'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:629:in `execute'
c:/Users/jmeridth/code/openstack-guest-agents/ipv6/windows/xenserver/rakefile.rb:49:in `block in <top (required)>'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:634:in `call'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:629:in `each'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:629:in `execute'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:595:in `block in invoke_with_call_chain'
c:/Ruby192/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:605:in `block in invoke_prerequisites'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:602:in `each'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:602:in `invoke_prerequisites'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:594:in `block in invoke_with_call_chain'
c:/Ruby192/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:581:in `invoke'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2041:in `invoke_task'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2019:in `block (2 levels) in top_level'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2019:in `each'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2019:in `block in top_level'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2058:in `standard_exception_handling'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:2013:in `top_level'
c:/Ruby192/lib/ruby/1.9.1/rake.rb:1992:in `run'
c:/Ruby192/bin/rake:31:in `<main>'
```

Yes, I will look at this on my own and issue pull request if I can ;)  Wanted it logged here though.

I know you have other generic ZipTask issues.  This one is pretty specific.

**Comment by mxriverlynn** [comment]
can you post your zip task configuration? i think it's a simple issue, but i need to see how you're setting the #additional_files to know for sure.

**Comment by jmeridth** [comment]
``` ruby
namespace :service do
  zip do |zip|
    file = 'Source.zip'
    File.delete(file) if File.exists?(file)
    zip.output_path = BUILDS_DIR
    zip.directories_to_zip SOURCE_DIR
    zip.additional_files = "installsource.bat"
    zip.output_file = file
    puts "zip file created"
  end
end
```

**Comment by mxriverlynn** [comment]
i suspected as much. do this instead:

zip do |zip|
  zip.additional_files "installsource.bat"
end

or

zip do |zip|
  zip.additional_files = ["installsource.bat"]
end

one of those two should work. 

i think you found a bug in my *args handling for array attributes. :)

**Comment by jmeridth** [comment]
that worked.

Thanks Derick.

I'll let you close the issue unless you want to let me issue pull request this weekend ;)
